---
heat_template_version: 2015-04-30

description: HOT to have a consistent number of VM

resources:
  Network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true

  Subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 10.10.10.0/24
      dns_nameservers: [8.8.8.8, 8.8.4.4]
      enable_dhcp: true
      gateway_ip: 10.10.10.1
      network_id: { get_resource: Network }

  Router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true

  _routerport:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: Router }
      subnet_id: { get_resource: Subnet }

  InitGroup:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::VM::LifeCycle
        properties:
          network_id: {get_resource: Network }
